### ISSUE TITLE
Beikoku great houses keep changing [Problem found]

### ISSUE THREAD

**Issue by DarkNinja3141** [Ofaloaf/postapoc#45]
The great houses in Beikoku keep changing. The former patricians are deported to other courts.

I am playing as the king of The Valley

EDIT: Also, my game started lagging and crashed
EDIT: The leader of Beikoku being imprisoned doesn't affect the constant great house change

EDIT: Okay, so I changed them to a merchant republic, it kept happening, but once I gave them land via console (I gave them San Juan Islands) it stopped. I think the bug is due to Beikoku being unlanded. I think there should be an event that gives them land when they spawn so that the bug doesn't keep happening. The Russians haven't colonized in my game yet, so I'll watch to see if the same bug occurs

**Comment by SteelyGlint** [comment]
I've got at least a partial fix for this bug. The invaders will now start off feudal, and only change to colonial_government when they win the invasion. As long as they haven't yet won an invasion, we should avoid the flood of shinto/edokko courtiers.

I need to do further testing to see what happens if they win an invasion, then lose all their holdings.

**Comment by SteelyGlint** [comment]
I added another event to revert invaders back to feudal if they lose all their holdings. 

This should clear up the last of the problems related to this issue. Let me know if any problems show up after the "Pirate traits event + Pacific invaders cleanup" commit.
