### ISSUE TITLE
Game crashes when hiring mercs

### ISSUE THREAD

**Issue by Mo1tke** [Ofaloaf/postapoc#90]
Playing as horselord of Saskatchewan, i hired the Lekwiltok Kiidaaw and then my game crashes.

**Comment by SteelyGlint** [comment]
Probably caused by this bug: https://github.com/Ofaloaf/postapoc/issues/11

We never figured out how to prevent the intermittent crash when hiring mercs with boats as an inland ruler. I thought we had just removed all mercs that had boats, but presumably a new one was added on the Pacific when we forgot about the bug.
